version: "3.8"
services:

  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 4080:80
    environment:
      TZ: ${TZ}
    depends_on:
    - fpm
    volumes:
    - .:/var/www/web
    - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build: .
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DOMAIN: ${DOMAIN}
      WEBSITE: ${WEBSITE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      NOREPLY_EMAIL: ${NOREPLY_EMAIL}
      API_URL: ${API_URL}
      API_KEY: ${API_KEY}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      RECAPTCHA_V2_SITEKEY: ${RECAPTCHA_V2_SITEKEY}
      RECAPTCHA_V2_SECRET: ${RECAPTCHA_V2_SECRET}
      RECAPTCHA_V3_SITEKEY: ${RECAPTCHA_V3_SITEKEY}
      RECAPTCHA_V3_SECRET: ${RECAPTCHA_V3_SECRET}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_DOMAIN_KEY: ${MAILGUN_DOMAIN_KEY}
      RYBBIT_WEBSITE: ${RYBBIT_WEBSITE}
      RYBBIT_SITE_ID: ${RYBBIT_SITE_ID}
    volumes:
      - .:/var/www/web
